### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by j-bialkowski** [voxeet/voxeet-sdk-android#17]
Hi,

We use in our app your SDK and we noticed in our crashlytics following OOM issue:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 684664 free bytes and 668KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
       at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
       at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:937)
       at java.lang.StringBuilder.substring(StringBuilder.java:77)
       at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:882)
       at java.lang.StringBuilder.substring(StringBuilder.java:77)
       at com.android.internal.os.LoggingPrintStream.flush(LoggingPrintStream.java:104)
       at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:294)
       at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:770)
       at java.lang.Throwable.printStackTrace(Throwable.java:678)
       at java.lang.Throwable.printStackTrace(Throwable.java:663)
       at java.lang.Throwable.printStackTrace(Throwable.java:654)
       at com.voxeet.audio2.manager.bluetooth.BluetoothHelper._invokeGetActiveDevice(BluetoothHelper.java:75)
       at com.voxeet.audio2.manager.bluetooth.BluetoothHelper.lambda$getActiveDevice$0(BluetoothHelper.java:32)
       at com.voxeet.audio2.manager.bluetooth.BluetoothHelper.$r8$lambda$lk1ifsRUzaLd5uN2o1UDXHOg484(BluetoothHelper.java)
       at com.google.android.datatransport.cct.CctTransportBackend$$InternalSyntheticLambda$5$336599f63a7da87e09aad74b29d82ad56f2f4bae9c20995e3c2332eee6757743$0.apply$bridge(CctTransportBackend.java:47)
       at com.voxeet.audio.utils.__Opt$Then.orNull(__Opt.java:86)
       at com.voxeet.audio2.manager.bluetooth.BluetoothHelper.getActiveDevice(BluetoothHelper.java:32)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$InternalSyntheticLambda$6$ceeb8383a83a1f81d4dc191b62a96e3726169873abab997218a1ff0ada4df541$0.apply$bridge(SQLiteEventStore.java:117)
       at com.voxeet.audio.utils.__Opt$Then.orNull(__Opt.java:86)
       at com.voxeet.audio2.manager.bluetooth.BluetoothHeadsetServiceListener.getActiveDevice(BluetoothHeadsetServiceListener.java:93)
       at com.voxeet.audio2.manager.BluetoothHeadsetDeviceManager.lambda$new$0(BluetoothHeadsetDeviceManager.java:89)
       at com.voxeet.audio2.manager.BluetoothHeadsetDeviceManager.$r8$lambda$9FJS5R6nBcOJx_D6GTNyk6Qf0mE(BluetoothHeadsetDeviceManager.java)
       at androidx.profileinstaller.ProfileInstallerInitializer$$InternalSyntheticLambda$1$0f795b3312dc1da540aed76dfe7be9153bc2dd822b10dd31dcd76fb9862960b5$0.run$bridge(ProfileInstallerInitializer.java:105)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Version: 3.8.0
`BLUETOOTH_CONNECT` permission not granted and not not requested

Can you take a look on that? As this issue is one of our highest frequent issues within the app

**Comment by codlab** [comment]
This is two separate issue. The first one, the OOM is most likely something from your app and have a side effect on the various components which are running.

Regarding the bluetooth_connect permission, this is a permission which needs to be granted in order for apps to properly get the list of devices and request connecting to them

**Comment by j-bialkowski** [comment]
As for the `bluetooth_connect`: it is runtime permission and user can deny this one when asked.
I wanted to put the `bluetooth_connect` permission piece in informations to put more light into the issue we encounter.

From the code I can see that `BluetoothHelper` uses reflection to obtain the active device there, then it crashes due to missing permission and OOM is thrown somewhere between.

For me it looks like the SDK should verify whether permission is granted and do not attempt to look for the devices if the permission is denied.

**Comment by codlab** [comment]
Answering a bit late...

`For me it looks like the SDK should verify whether permission is granted and do not attempt to look for the devices if the permission is denied.`

Unfortunately one goal of this method is to be able to be used also outside of Context-aware situations for some legacy support.

`it crashes due to missing permission`

The exception is caught, it's a safe call :)

`OOM is thrown somewhere between`

The specific OOM in the stack trace is due to the string allocation & manipulation inside the Throwable.printStackTrace but as I mentioned, it is most likely due to overall stress on the app's memory and it happen that it crashed at that point but it could have crashed at any other places which were asking for some memory to be made available.

OOM can be due to anything such as heavy images being loaded up but not freed, etc... We also noticed a possible issue in our new feature that helps developer integrate their own audio callback, so if you were using this feature, it could also be a possible source for this OOM issue (regarding the later, 3.9.0 fixes this)
