### ISSUE TITLE
Error creating conference on the Android emulator

### ISSUE THREAD

**Issue by vodemn** [voxeet/voxeet-sdk-android#23]
Hello! I'm trying to create and join a conference on Android simulator and I'm getting this error:
```
W/System.err(12774): com.voxeet.android.media.errors.RemoteDescriptionError: Unable set remote SDP for Peer: 9e9cf9d6-427b-333e-be3a-774a40962007 :: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'.
W/System.err(12774): 	at com.voxeet.sdk.media.MediaSDK.lambda$createAnswerForPeer$0$com-voxeet-sdk-media-MediaSDK(MediaSDK.java:108)
W/System.err(12774): 	at com.voxeet.sdk.media.MediaSDK$$ExternalSyntheticLambda2.run(Unknown Source:14)
W/System.err(12774): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
W/System.err(12774): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err(12774): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err(12774): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err(12774): 	at java.lang.Thread.run(Thread.java:1012)
```

So my question is it even possible to run a voxeet app on the emulator? Or it is suitable only for real devices?

**My setup**
macOS 13.2.1 22D68 darwin-arm
Android 13.0 arm64-v8a

**Comment by FabienLavocat** [comment]
Hi @vodemn, this looks like the device does not support the video codec. Could you please create the conference using the VP8 video codec.

**Comment by FabienLavocat** [comment]
I'll close this issue for now, if you are still having issue, please reopen it.
